import { createDefaultDashboardApplicationV3, type DashboardComponentV3 } from '../models/dashboard-v3.ts'
import type { AnalysisConfig } from '../models/dashboard.ts'
import { validateDashboardApplicationV3 } from './dashboardValidationV3.ts'
export interface HospitalModelPlan { schemaVersion: 1; template: 'hospital-overview'; title: string; month: string; comparison: 'yoy' | 'mom'; sections: string[]; notes: string }
function analysis(overrides: Partial<AnalysisConfig> = {}): AnalysisConfig {
  return { xMin: null, xMax: null, yLeftMin: null, yLeftMax: null, yRightMin: null, yRightMax: null, showLabels: false, labelDecimals: 1, labelPosition: 'inside', labelMode: 'percentage', labelShowCategory: false, labelShowSeries: false, labelUnit: '', percentageBase: 'category', leftAxisTitle: '', leftAxisUnit: '', leftAxisColor: '#8c9bb1', rightAxisTitle: '', rightAxisUnit: '', rightAxisColor: '#8c9bb1', legendVisible: true, legendPosition: 'bottom', warningLines: [], ...overrides }
}
export function createHospitalOverviewDraft(plan: HospitalModelPlan, months: string[], requestId: string, provider = 'chatgpt-web-codex') {
  const id = `hospital-ai-${crypto.randomUUID()}`, app = createDefaultDashboardApplicationV3({ id, name: plan.title, pageName: '医院概览' }), page = app.pages[0]!, monthId = `${id}-month`
  Object.assign(page.canvas, { width: 1500, height: 936, background: '#eef3fb', showGrid: false }); page.titleStyle.show = false
  app.theme.tokens = { panelBackground: '#ffffff', panelBorder: '#e7edf6', panelRadius: 10, textPrimary: '#203452', textSecondary: '#8190a5' }
  app.parameters = [{ id: monthId, code: 'overview_month', name: '月份', type: 'singleSelect', scope: 'application', required: false, defaultValue: plan.month, source: { kind: 'static', options: months.map(m => ({ label: m, value: m })) } }]
  page.controls = [{ id: `${id}-month-control`, type: 'singleSelect', parameterIds: [monthId], position: { x: 0, y: 0, width: 240, height: 56, zIndex: 1 }, styleConfig: {}, interaction: { submitMode: 'immediate', clearable: false } }]
  const components: DashboardComponentV3[] = []
  const chart = (key: string, type: DashboardComponentV3['type'], title: string, x: number, y: number, width: number, height: number, dimensions: string[], fields: string[], filtered = true) => {
    const c: DashboardComponentV3 = { id: `${id}-${key}-${components.length}`, type, title, position: { x, y, width, height, zIndex: 1 }, styleConfig: { background: '#fff', titleColor: '#263b58', titleSize: 15, titleWeight: 600, titleVisible: true, borderRadius: 10, borderColor: '#e7edf6', shadow: '0 3px 12px rgba(35,64,110,0.03)' }, dataConfig: { version: 3, sourceKind: 'server', datasetId: `local-overview:${key}`, dimensions: dimensions.map(field => ({ field, role: 'category' })), measures: fields.map(field => ({ field, aggregation: 'sum', alias: fields.length === 1 ? title.replace(/（.*?）| · .*/g, '') : field, chartType: type === 'line' ? 'line' : 'bar', axis: 'left' })), filters: [], sort: [], limit: 200, parameterBindings: filtered ? [{ datasetParameterCode: 'month', parameterId: monthId }] : [], refreshPolicy: 'onParameterChange' } }
    if (type === 'kpi') { const people = key.includes('visits') || key === 'discharges'; c.kpiConfig = { primaryMeasureField: 'value', unit: key.includes('rate') || key === 'bed_utilization' ? '%' : people ? '人次' : key.includes('avg') ? '元' : '万元', decimals: people ? 0 : 2, useGrouping: true, yoyField: '', momField: '', positiveColor: '#12b76a', negativeColor: '#e34d59', targetMode: 'field', targetValue: 0, targetField: 'budget', showProgress: false, progressColor: '#2855ff' } }
    else if (type !== 'table') c.analysisConfig = analysis(type === 'pie' ? { showLabels: true } : {})
    if (type === 'table') { c.tableConfig = { columns: [...dimensions.map(field => ({ field, label: field === 'dept_name' ? '科室' : '分类', width: 210, format: 'auto' as const, summary: 'none' as const })), ...fields.map(field => ({ field, label: '收入（万元）', width: 130, format: 'number' as const, summary: 'none' as const }))], striped: true, showHeader: true, pagination: { enabled: true, mode: 'client', pageSize: 6, showTotal: true } }; c.dataConfig.sort = [{ field: 'value', direction: 'desc' }] }
    components.push(c); return c
  }
  const text = (key: string, content: string, x: number, y: number, width: number, height: number, fontSize: number, color: string, weight = 400, background = '#eef3fb') => {
    components.push({ id: `${id}-${key}`, type: 'text', title: key, position: { x, y, width, height, zIndex: 1 }, styleConfig: { background, titleColor: color, titleSize: fontSize, titleWeight: weight, titleVisible: false, borderWidth: 0, borderRadius: 8, shadow: 'none' }, dataConfig: { version: 3, sourceKind: 'mock', datasetId: '', dimensions: [], measures: [], filters: [], sort: [], limit: 200, parameterBindings: [], refreshPolicy: 'manual' }, textConfig: { content, color, fontSize, fontWeight: weight, align: 'left', verticalAlign: 'center', lineHeight: 1.6 } })
  }
  text('masthead', '医院运营概览', 24, 16, 630, 48, 29, '#2855ff', 700)
  text('edition', '经营监测   /   本地试用 · 知识口径暂定', 1092, 22, 384, 36, 12, '#8190a5')
  if (plan.sections.includes('summary')) ['total_revenue', 'medical_revenue', 'total_cost', 'surplus_rate'].forEach((key, i) => chart(key, 'kpi', ['总收入', '医疗收入', '总成本', '结余率'][i]!, 24 + i % 2 * 268, 82 + Math.floor(i / 2) * 156, 256, 144, [], ['value']))
  if (plan.sections.includes('operations')) ['outpatient_revenue', 'outpatient_visits', 'outpatient_avg', 'inpatient_revenue', 'discharges', 'inpatient_avg', 'bed_utilization'].forEach((key, i) => { const c = chart(key, 'kpi', ['门诊收入', '门急诊人次', '门诊次均费用', '住院收入', '出院人次', '住院次均费用', '病床使用率'][i]!, 572 + i * 130, 82, 124, 144, [], ['value']); c.styleConfig.titleSize = 12 })
  if (plan.sections.includes('trend')) { const c = chart('medical_revenue', 'line', '医疗收入趋势（万元）', 572, 238, 492, 284, ['month'], ['value'], false); c.dataConfig.datasetId = `local-overview:medical_revenue:${plan.month.slice(0, 4)}-01:${plan.month}`; c.dataConfig.measures[0]!.alias = '医疗收入'; c.dataConfig.sort = [{ field: 'month', direction: 'asc' }] }
  if (plan.sections.includes('departments')) chart('departments', 'table', '科室收入排行', 1076, 238, 400, 284, ['dept_name'], ['value'])
  if (plan.sections.includes('composition')) { chart('composition', 'pie', '收入结构', 572, 534, 256, 310, ['category'], ['value']); chart('service_composition', 'pie', '医疗服务明细', 840, 534, 256, 310, ['category'], ['value']) }
  if (plan.sections.includes('beds')) { const c = chart('beds', 'scatter', '床位使用与周转', 1108, 534, 368, 310, ['dept_name'], ['x', 'y']); c.dataConfig.measures[0]!.alias = '周转次数'; c.dataConfig.measures[1]!.alias = '使用率'; c.analysisConfig = analysis({ legendVisible: false, leftAxisTitle: '周转次数', rightAxisTitle: '使用率', rightAxisUnit: '%' }) }
  if (plan.sections.includes('costs')) { const c = chart('cost_structure', 'bar', '成本构成（万元）', 24, 394, 524, 450, ['category'], ['value']); c.analysisConfig = analysis({ legendVisible: false }) }
  text('source', `本地 ADS 只读快照 · 预算暂无数据 · 床位口径暂定，零值按原值展示\n趋势为生成时本年截至月；其余区域随顶部月份切换。方案来源：${provider} · 标识 ${requestId}`, 24, 860, 1452, 56, 11, '#8190a5')
  page.components = components; app.extensionRefs.localGeneration = { provider, requestId, plan: structuredClone(plan), dataMode: 'bd_odr_readonly_ads_snapshot', visualTemplate: 'hospital-overview-blue-v2' }
  const result = validateDashboardApplicationV3(app); if (!result.valid) throw new Error(result.issues.map(i => i.message).join('；')); return app
}
