<script setup lang="ts">
import type { TableConfig, TableConditionalRuleConfig } from '../models/dashboard.ts'
const props = defineProps<{ config: TableConfig; fields: Array<{ name: string; label: string }> }>()
const emit = defineEmits<{ dirty: [] }>()
function ensureConfig() { props.config.fixedHeader ??= true; props.config.pagination ??= { enabled: true, mode: 'client', pageSize: 20, showTotal: true }; props.config.conditionalRules ??= [] }
function addRule() { ensureConfig(); const field = props.config.columns[0]?.field || props.fields[0]?.name || ''; const rule: TableConditionalRuleConfig = { id: `table-rule-${crypto.randomUUID()}`, field, operator: 'gte', value: 0, backgroundColor: '#fee2e2', textColor: '#991b1b', badge: 'danger' }; props.config.conditionalRules!.push(rule); emit('dirty') }
function removeRule(index: number) { props.config.conditionalRules?.splice(index, 1); emit('dirty') }
ensureConfig()
</script>
<template>
  <section class="property-section"><h3><span>01</span>表格与分页</h3>
    <div class="switch-row"><span>显示表头</span><input v-model="config.showHeader" type="checkbox" @change="emit('dirty')" /></div><div class="switch-row"><span>固定表头</span><input v-model="config.fixedHeader" type="checkbox" @change="emit('dirty')" /></div><div class="switch-row"><span>斑马纹</span><input v-model="config.striped" type="checkbox" @change="emit('dirty')" /></div><div class="switch-row"><span>启用分页</span><input v-model="config.pagination!.enabled" type="checkbox" @change="emit('dirty')" /></div>
    <div v-if="config.pagination!.enabled" class="number-pair"><label>分页模式<select v-model="config.pagination!.mode" @change="emit('dirty')"><option value="client">客户端</option><option value="server">服务端</option></select></label><label>每页条数<input v-model.number="config.pagination!.pageSize" type="number" min="1" max="200" @change="emit('dirty')" /></label></div><div class="switch-row"><span>显示总数</span><input v-model="config.pagination!.showTotal" type="checkbox" @change="emit('dirty')" /></div>
    <h3><span>02</span>列配置</h3><div v-for="column in config.columns" :key="column.field" class="table-column-config"><input v-model="column.label" placeholder="列名" @input="emit('dirty')" /><input v-model.number="column.width" type="number" min="60" max="600" title="列宽" @change="emit('dirty')" /><select v-model="column.format" title="格式" @change="emit('dirty')"><option value="auto">自动</option><option value="number">数值</option><option value="percentage">百分比</option><option value="date">日期</option></select><select v-model="column.summary" title="汇总" @change="emit('dirty')"><option value="none">不汇总</option><option value="sum">合计</option><option value="avg">平均</option><option value="count">计数</option></select></div>
    <div class="warning-heading"><b>条件格式与风险色</b><button type="button" @click="addRule">添加规则</button></div><article v-for="(rule, index) in config.conditionalRules" :key="rule.id" class="table-rule-config"><select v-model="rule.field" @change="emit('dirty')"><option v-for="field in fields" :key="field.name" :value="field.name">{{ field.label }}</option></select><select v-model="rule.operator" @change="emit('dirty')"><option value="eq">等于</option><option value="ne">不等于</option><option value="gt">大于</option><option value="gte">大于等于</option><option value="lt">小于</option><option value="lte">小于等于</option><option value="contains">包含</option><option value="isNull">为空</option><option value="notNull">非空</option></select><input v-if="!['isNull','notNull'].includes(rule.operator)" v-model="rule.value" placeholder="阈值/文本" @input="emit('dirty')" /><select v-model="rule.badge" @change="emit('dirty')"><option :value="undefined">无风险标签</option><option value="normal">正常</option><option value="warning">预警</option><option value="danger">危险</option></select><label>背景<input v-model="rule.backgroundColor" type="color" @input="emit('dirty')" /></label><label>文字<input v-model="rule.textColor" type="color" @input="emit('dirty')" /></label><button type="button" @click="removeRule(index)">删除规则</button></article>
  </section>
</template>
<style scoped>.table-rule-config{display:grid;grid-template-columns:1fr 1fr;gap:8px;padding:10px;margin:8px 0;border:1px solid #dfe7ef;border-radius:7px}.table-rule-config>button{grid-column:1/-1}.table-rule-config label{display:flex;align-items:center;justify-content:space-between;gap:8px}.table-rule-config input[type=color]{width:44px}</style>
